apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_hba.conf: |
    # Allow local connections
    local   all             all                                     trust
    # Allow connections from localhost
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    # Allow all external connections with md5 authentication
    host    all             all             0.0.0.0/0               md5
    host    all             all             ::/0                    md5
