quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = postgres
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.http.port=8080
quarkus.http.root-path=/api

#oidc
quarkus.oidc-client.auth-server-url=https://auth.htl-leonding.ac.at/realms/2425-5bhitm/
quarkus.oidc-client.client-id=maturaballmanager
quarkus.oidc-client.credentials.secret=C4bc62f5JmmJVMK1Iu6qTmHUdMm0eO8C
quarkus.rest-client.oidc-client.url=https://auth.htl-leonding.ac.at/realms/2425-5bhitm

# jwt
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=https://auth.htl-leonding.ac.at/realms/2425-5bhitm/protocol/openid-connect/certs

#ngrok
#quarkus.ngrok.auth-token=2EoiTEDk94zVBMyNllz2YbKjJxU_4uxcaijageWBwNHrmZi15