########################################
# QUARKUS DEPLOYMENT + SERVICE
########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/htl-leo-itp-2325-4-5bhitm/leoball-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: minio-secrets
            - secretRef:
                name: quarkus-secrets
            - secretRef:
                name: postgres-secrets
          livenessProbe:
            httpGet:
              path: /api/q/health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/q/health/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
