quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.db-kind=postgresql
quarkus.datasource.username=maturaballmanager
quarkus.datasource.password=maturaballmanager
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:12345/maturaballmanager
quarkus.datasource.jdbc.max-size=16