quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.username=maturaballmanager
quarkus.datasource.password=maturaballmanager
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:18700/maturaballmanager
quarkus.datasource.jdbc.max-size=16
quarkus.http.port=8081

quarkus.http.cors=true