quarkus.oidc.auth-server-url=https://auth.htl-leonding.ac.at/realms/2425-5bhitm
quarkus.oidc.client-id=maturaballmanager
quarkus.oidc.credentials.secret=aKC4wP9DvCh5biqLAyerxJnopVH4zVHI
quarkus.oidc.application-type=web-app
quarkus.oidc.token-path=/protocol/openid-connect/token
quarkus.http.auth.proactive=true

quarkus.api.path=/api