###
POST http://localhost:9999/api/companies/addCompany
Content-Type: application/json

{
  "name": "Facebook",
  "website": "",
  "contactPerson": {},
  "address": {}
}

###
GET http://localhost:9999/api/companies/overview
Content-Type: application/json



###
GET http://localhost:9999/api/companies/
###
GET http://localhost:9999/api/addresses/
###
GET http://localhost:9999/api/contactpersons/