# File: .github/workflows/quarkus.yml
name: Build and Test Quarkus

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout das Repository ins richtige Verzeichnis
      - name: Checkout code
        run: git clone https://github.com/htl-leo-itp-2325-4-5BHITM/Maturaballmanager.git
      - name: Checkout to dev branch
        run: cd Maturaballmanager && git checkout dev
      # Prüfen, ob das Verzeichnis existiert
      - name: Verify backend directory
        run: ls -la app/backend

      # Manuelle Installation von JDK 11
      - name: Install JDK 11
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version

      # Build und Test des Quarkus Projekts
      - name: Build with Maven
        working-directory: app/backend
        run: mvn clean package

      - name: Run tests
        working-directory: app/backend
        run: mvn test

